# Generated by Django 5.1.7 on 2026-09-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromosome', models.CharField(max_length=32)),
                ('position', models.PositiveBigIntegerField()),
                ('ref', models.TextField()),
                ('alt', models.TextField()),
                ('gt', models.CharField(max_length=64)),
            ],
            options={
                'indexes': [models.Index(fields=['chromosome', 'position'], name='genotype_chr_pos_idx')],
            },
        ),
    ]
